USE ECOMMERCE;

-- RELAÇÃO DE PEDIDO JÁ ENVIADOS
SELECT ORD.IDORDER AS ID_PEDIDO, 
       CASE
           WHEN ORD.SENDVALUE IS NULL THEN FORMAT(0.00,2)
           ELSE FORMAT(ORD.SENDVALUE,2)
        END AS VALOR_FRETE, 
        DISP.COMPANY AS TRANSPORTADORA,
        DATE_FORMAT(DISP.SEND_DATE, '%d-%m-%Y') AS DATA_ENVIO, 
        DISP.IDTRACKING AS CODIGO_RASTREIO,
	    DISP.STATUS AS  SITUAÇÃO
FROM ORDERS AS ORD
INNER JOIN DISPATCHS AS DISP ON  DISP.IDDISPORDER = ORD.IDORDER;



-- RELAÇÃO DOS TIPOS DE PAGAMENTO, QUANTIDADE DE CADA UM E O PERCENTUAL 
SELECT DESCRIÇÃO, TOTAL_POR_TIPO, TRUNCATE(((RP.TOTAL_POR_TIPO/TOTAL_PAGAMENTOS)*100),2) AS PERCENTUAL
FROM 
     ( SELECT PA.TYPEPAYMENT AS DESCRIÇÃO, 
       COUNT(*) AS TOTAL_POR_TIPO,
       (SELECT COUNT(*) AS TOTAL_PAGAMENTOS FROM   PAYMENTS AS PY )  AS TOTAL_PAGAMENTOS
       FROM ORDERS AS OD
       INNER JOIN PAYMENTS AS PA  ON OD.IDORDER=PA.IDPAYMORDER
       GROUP BY PA.TYPEPAYMENT
      ) AS RP;



-- LISTA QUANTIDADE DE PEDIDOS POR CLIENTE
SELECT CLI.FNAME AS PRIMEIRO_NOME, COUNT(*) AS QUANTIDADE_DE_PEDIDOS
FROM clients AS CLI
INNER JOIN orders ORD  ON ORD.IDORDERCLIENT=CLI.IDCLIENT
GROUP BY ORD.IDORDERCLIENT;

-- LISTA VENDEDOR QUE TAMBÉM É FORNECEDOR
SELECT CONCAT(SEL.CNPJ,' ', SEL.SOCIALNAME ) AS VENDEDOR, 
       CONCAT(SUP.CNPJ,' ', SUP.SOCIALNAME)  AS FORNECEDOR
FROM SELLER AS SEL, SUPPLIER AS SUP
WHERE  SEL.CNPJ = SUP.CNPJ;


-- RELAÇÃO DE PRODUTOS FORNECEDORES E ESTOQUES
SELECT PROD.IDPRODUCT AS ID_PRODUTO, PROD.PNAME AS NOME_PRODUTO, SOCIALNAME AS FORNECEDOR, PROD_FORNEC.QUANTITY AS QUANTIDADE
FROM PRODUCT PROD
INNER JOIN  PRODUCTSUPPLIER PROD_FORNEC  ON PROD_FORNEC.IDPSPRODUCT=PROD.IDPRODUCT
INNER JOIN  SUPPLIER FORNEC              ON FORNEC.IDSUPPLIER=PROD_FORNEC.IDPSSUPPLIER 
ORDER BY PROD.IDPRODUCT;


-- RELAÇÃO DE NOMES DOS FORNECEDORES E NOMES DOS PRODUTOS
SELECT  SOCIALNAME AS FORNECEDOR, PROD.PNAME AS NOME_PRODUTO
FROM SUPPLIER AS FORNEC 
INNER JOIN  PRODUCTSUPPLIER AS PROD_FORNEC  ON PROD_FORNEC.IDPSSUPPLIER=FORNEC.IDSUPPLIER
INNER JOIN  PRODUCT         AS PROD         ON PROD.IDPRODUCT=PROD_FORNEC.IDPSPRODUCT 
ORDER BY FORNEC.SOCIALNAME;
		
		
-- RELAÇÃO DE FORNECEDORES COM PRODUTODOS EM ESTOQUE ACIMA DE 500 QUANTIDADES		
SELECT FORNEC.SOCIALNAME AS FORNECEDOR, SUM(PROD_FORNEC.QUANTITY) AS QUANTIDADE
FROM SUPPLIER AS FORNEC
INNER JOIN  PRODUCTSUPPLIER AS PROD_FORNEC  ON FORNEC.IDSUPPLIER=PROD_FORNEC.IDPSSUPPLIER
GROUP BY FORNEC.SOCIALNAME
HAVING QUANTIDADE > 500;