DROP DATABASE ECOMMERCE;
CREATE DATABASE ECOMMERCE;

USE ECOMMERCE;


-- 1 CRIAR TABELA CLIENTES 

CREATE TABLE CLIENTS (
  IDCLIENT    INT NOT NULL AUTO_INCREMENT,
  FNAME       VARCHAR(10) NOT NULL,
  MINIT       CHAR(3),
  LNAME       VARCHAR(20),
  CLIENT_TYPE ENUM('PF', 'PJ') NOT NULL,
  CPF_CNPJ    VARCHAR(14)  NOT NULL,
  ADDRESS     VARCHAR(255),
  DATEBIRTH   DATE,
  PRIMARY KEY (IDCLIENT),
  UNIQUE KEY UNIQUE_CPF_CLIENT (CPF_CNPJ),
  CONSTRAINT CLIENTS_CHK_1 CHECK ((CLIENT_TYPE ='PJ' AND LENGTH(CPF_CNPJ) = 14) OR
                                  (CLIENT_TYPE ='PF' AND LENGTH(CPF_CNPJ) = 11))
);

ALTER TABLE CLIENTS AUTO_INCREMENT = 1;


-- 2 CRIAR TABELA PRODUTO 

CREATE TABLE PRODUCT (
  IDPRODUCT   INT NOT NULL AUTO_INCREMENT,
  PNAME       VARCHAR(255) NOT NULL,
  CLASSIFICATION_KIDS TINYINT(1) DEFAULT '0',
  CATEGORY    ENUM('ELETRÔNICO','VESTIMENTA','BRINQUEDOS','ALIMENTOS','MÓVEIS') NOT NULL,
  PAVALIATION FLOAT DEFAULT '0',
  PSIZE       VARCHAR(10) COMMENT 'DIMENSÃO DO PRODUTO',
  PRIMARY KEY (IDPRODUCT)
); 

ALTER TABLE PRODUCT AUTO_INCREMENT = 1;

-- 3 CRIAR TABELA PEDIDOS

CREATE TABLE ORDERS (
  IDORDER          INT NOT NULL AUTO_INCREMENT,
  IDORDERCLIENT    INT NOT NULL,
  ORDERSTATUS      ENUM('CANCELADO','CONFIRMADO','EM PROCESSAMENTO') DEFAULT 'EM PROCESSAMENTO',
  ORDERDESCRIPTION VARCHAR(255),
  SENDVALUE        FLOAT DEFAULT '10',
  TOTALVALUEORDER  FLOAT,
  PAYMENTCASH      TINYINT(1) DEFAULT '0',
  PRIMARY KEY (IDORDER,IDORDERCLIENT),
  CONSTRAINT FK_ORDES_CLIENT FOREIGN KEY (IDORDERCLIENT) REFERENCES CLIENTS (IDCLIENT) ON UPDATE CASCADE
);

ALTER TABLE ORDERS AUTO_INCREMENT = 1;

-- 4 CRIAR TABELA PAGAMENTOS
CREATE TABLE PAYMENTS (
  IDPAYMORDER     INT NOT NULL,
  IDPAYMCLIENT    INT NOT NULL,
  IDPAYMENT       INT NOT NULL,
  TYPEPAYMENT     ENUM('BOLETO','CARTÃO','DOIS CARTÕES') NOT NULL,
  LIMITAVAILABLE  FLOAT NOT NULL,
  PRIMARY KEY (IDPAYMORDER,IDPAYMCLIENT,IDPAYMENT),
  CONSTRAINT FK_PAYMENTS_ORDERS FOREIGN KEY (IDPAYMORDER, IDPAYMCLIENT) REFERENCES ORDERS (IDORDER, IDORDERCLIENT)
);

-- 5 CRIAR TABELA DESPACHO_PEDIDO
CREATE TABLE DISPATCHS (
  IDDISPORDER     INT NOT NULL,
  IDDISPCLIENT    INT NOT NULL,
  IDDISPATCH      INT NOT NULL,
  COMPANY         VARCHAR(255) NOT NULL,
  CONTACT         CHAR(11) NOT NULL,
  SEND_DATE       DATE NOT NULL,
  IDTRACKING      VARCHAR(45) NOT NULL,
  STATUS          ENUM('AGUARDANDO CARREGAMENTO','EM TRANSITO','ENTREGUE') NOT NULL,
  PRIMARY KEY (IDDISPORDER,IDDISPCLIENT,IDDISPATCH),
  CONSTRAINT FK_DISPATCHS_ORDERS FOREIGN KEY (IDDISPORDER, IDDISPCLIENT) REFERENCES ORDERS (IDORDER, IDORDERCLIENT)
); 



-- 6 CRIAR TABELA ESTOQUE

CREATE TABLE PRODUCTSTORAGE (
  IDPRODSTORAGE    INT NOT NULL AUTO_INCREMENT,
  STORAGELOCATION  VARCHAR(255) NOT NULL,
  QUANTITY         INT DEFAULT '0' NOT NULL,
  PRIMARY KEY (IDPRODSTORAGE)
);


ALTER TABLE PRODUCTSTORAGE AUTO_INCREMENT = 1;

-- 7 CRIAR TABELA VENDEDOR

CREATE TABLE SELLER (
  IDSELLER     INT NOT NULL AUTO_INCREMENT,
  SOCIALNAME   VARCHAR(255) NOT NULL,
  ABSTNAME     VARCHAR(255),
  CNPJ         CHAR(15),
  CPF          CHAR(9),
  LOCATION     VARCHAR(255),
  CONTACT      CHAR(11) NOT NULL,
  PRIMARY KEY (IDSELLER),
  UNIQUE KEY UNIQUE_CNPJ_SELLER (CNPJ),
  UNIQUE KEY UNIQUE_CPF_SELLER (CPF)
);

ALTER TABLE SELLER AUTO_INCREMENT = 1;

-- 8 CRIAR TABELA FORNECEDOR

CREATE TABLE SUPPLIER (
  IDSUPPLIER    INT NOT NULL AUTO_INCREMENT,
  SOCIALNAME    VARCHAR(255) NOT NULL,
  CNPJ          CHAR(15) NOT NULL,
  CONTACT       CHAR(11) NOT NULL,
  PRIMARY KEY (IDSUPPLIER),
  UNIQUE KEY UNIQUE_SUPPLIER (CNPJ)
);

ALTER TABLE SUPPLIER AUTO_INCREMENT = 1;


-- 9 CRIAR TABELA PRODUTO_VENDEDOR

CREATE TABLE PRODUCTSELLER (
  IDPSELLER      INT NOT NULL,
  IDPPRODUCT     INT NOT NULL,
  PRODQUANTITY   INT DEFAULT '1',
  PRIMARY KEY (IDPSELLER,IDPPRODUCT),
  CONSTRAINT FK_PRODUCT_PRODUCT FOREIGN KEY (IDPPRODUCT) REFERENCES PRODUCT (IDPRODUCT),
  CONSTRAINT FK_PRODUCT_SELLER FOREIGN KEY (IDPSELLER) REFERENCES SELLER (IDSELLER)
);

-- 10 CRIAR TABELA PRODUTO_PEDIDOS

CREATE TABLE PRODUCTORDER (
  IDPOPRODUCT   INT NOT NULL,
  IDPOORDER     INT NOT NULL,
  POQUANTITY    INT NOT NULL DEFAULT '1',
  POSTATUS      ENUM('DISPONÍVEL','SEM ESTOQUE') DEFAULT 'DISPONÍVEL',
  PRIMARY KEY (IDPOPRODUCT,IDPOORDER),
  CONSTRAINT FK_PRODUCTORDER_ORDER FOREIGN KEY (IDPOORDER) REFERENCES ORDERS (IDORDER),
  CONSTRAINT FK_PRODUCTORDER_PRODUCT FOREIGN KEY (IDPOPRODUCT) REFERENCES PRODUCT (IDPRODUCT)
);

-- 11 CRIAR TABELA ESTOQUE_LOCALIZAÇÃO

CREATE TABLE STORAGELOCATION (
  IDLPRODUCT     INT NOT NULL,
  IDLSTORAGE     INT NOT NULL,
  LOCATION       VARCHAR(255) NOT NULL,
  PRIMARY KEY (IDLPRODUCT,IDLSTORAGE),
  CONSTRAINT FK_STORAGE_LOCATION_PRODUCT FOREIGN KEY (IDLPRODUCT) REFERENCES PRODUCT (IDPRODUCT),
  CONSTRAINT FK_STORAGE_LOCATION_STORAGE FOREIGN KEY (IDLSTORAGE) REFERENCES PRODUCTSTORAGE (IDPRODSTORAGE)
);


-- 12 CRIAR TABELA PRODUTO_FORNECEDOR

CREATE TABLE PRODUCTSUPPLIER (
  IDPSSUPPLIER      INT NOT NULL,
  IDPSPRODUCT       INT NOT NULL,
  QUANTITY          INT NOT NULL,
  PRIMARY KEY (IDPSSUPPLIER,IDPSPRODUCT),
  KEY FK_PRODUCT_SUPPLIER_PRODCUT (IDPSPRODUCT),
  CONSTRAINT FK_PRODUCT_SUPPLIER_PRODCUT FOREIGN KEY (IDPSPRODUCT) REFERENCES PRODUCT (IDPRODUCT),
  CONSTRAINT FK_PRODUCT_SUPPLIER_SUPPLIER FOREIGN KEY (IDPSSUPPLIER) REFERENCES SUPPLIER (IDSUPPLIER)
);




